<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width,initial-scale=1.0">
  <title>Async Await</title>
  <link rel="stylesheet" href="../base.css">
</head>

<body>
  <script>
    function wait(ms = 0) {
      return new Promise((resolve) => {
        setTimeout(resolve, ms);
      });
    }

    function makePizza(toppings = []) {
      return new Promise(function (resolve, reject) {
        // reject if people try with pineapple
        if (toppings.includes('pineapple')) {
          reject('Seriously? Get out üçç');
        }
        const amountOfTimeToBake = 500 + toppings.length * 200;
        // wait 1 second for the pizza to cook:
        setTimeout(function () {
          // when you are ready, you can resolve this promise
          resolve(`Here is your pizza üçï with the toppings ${toppings.join(' ')}`);
        }, amountOfTimeToBake);
        // if something went wrong, we can reject this promise;
      });
    }

    // async await function don't allow errors to go through and need ways to deal with catching said
    // errors.

    // TRY-EXCEPT
    // async function go() {
    //   try {
    //     const pizza = await makePizza(['pineapple']);
    //     console.log(pizza);
    //   } catch (err) {
    //     console.log('ERROR!');
    //     console.log(err);
    //   }
    // }

    // MIX AND MATCH FUNCTIONS WITH CATCH
    // (useful when you want to handle the error inside the actual function)
    // NOTE: A function marked "async" will automatically return a promise
    // (implies you can await async function themselves!)
    function handleError(err) {
      console.log('ERROR!');
      console.log(err);
    }

    async function go() {
      const pizza = await makePizza(['pep']).catch(handleError);
      console.log(pizza);
      return pizza;
    }

    // What wes uses most often to handle errors
    // Catch it at run time
    // go().catch(handleError);

    // Can also handle errors with a higher-order function (a function that returns another function)
    // Make a safe function with a High Order Function (HOF)
    // Beneficial because it allows for reproduciability accross functions
    function makeSafe(fn, errorHandler) {
      return function () {
        fn().catch(errorHandler);
      };
    }

    // go(); // Unsafe
    const safeGo = makeSafe(go, handleError);
    safeGo();

    // Could also catch when you call the function
    // go().catch(handleError);

    // async function goGo() {
    //   const result = await go();
    // }

    // goGo().catch(handleError);
  </script>
</body>

</html>